// @ts-nocheck
// This file is auto-generated by a GraphQL code generator.
// It is not recommended to modify this file directly.
// This schema has been massively expanded to represent the full, enterprise-grade data manifold of the Demo Bank application.

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Date: any;
  DateTime: any;
  JSON: any;
};

// ================================================================================================
// ENUMERATIONS
// ================================================================================================

export enum TransactionType {
  Expense = 'EXPENSE',
  Income = 'INCOME'
}

export enum TransactionStatus {
  Pending = 'PENDING',
  Posted = 'POSTED',
  Cleared = 'CLEARED',
  Failed = 'FAILED'
}

export enum AssetType {
  Stocks = 'STOCKS',
  Bonds = 'BONDS',
  Crypto = 'CRYPTO',
  RealEstate = 'REAL_ESTATE',
  Cash = 'CASH'
}

export enum PaymentOrderStatus {
  NeedsApproval = 'NEEDS_APPROVAL',
  Approved = 'APPROVED',
  Processing = 'PROCESSING',
  Completed = 'COMPLETED',
  Denied = 'DENIED',
  Returned = 'RETURNED'
}

export enum AnomalySeverity {
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH',
    Critical = 'CRITICAL'
}

export enum AnomalyStatus {
    New = 'NEW',
    UnderReview = 'UNDER_REVIEW',
    Dismissed = 'DISMISSED',
    Resolved = 'RESOLVED'
}

// ================================================================================================
// OBJECT TYPES
// ================================================================================================

export type User = {
  __typename?: 'User';
  id: Scalars['ID'];
  name: Scalars['String'];
  email: Scalars['String'];
  createdAt: Scalars['DateTime'];
  gamification: GamificationState;
  rewardPoints: RewardPoints;
  preferences: UserPreferences;
};

export type UserPreferences = {
    __typename?: 'UserPreferences';
    theme: Scalars['String'];
    notifications: NotificationPreferences;
}

export type NotificationPreferences = {
    __typename?: 'NotificationPreferences';
    email: Scalars['Boolean'];
    push: Scalars['Boolean'];
};

export type Transaction = {
  __typename?: 'Transaction';
  id: Scalars['ID'];
  type: TransactionType;
  status: TransactionStatus;
  category: Scalars['String'];
  description: Scalars['String'];
  amount: Scalars['Float'];
  date: Scalars['Date'];
  merchant?: Maybe<Merchant>;
  carbonFootprint?: Maybe<Scalars['Float']>;
};

export type Merchant = {
    __typename?: 'Merchant';
    id: Scalars['ID'];
    name: Scalars['String'];
    logoUrl?: Maybe<Scalars['String']>;
};

export type Asset = {
  __typename?: 'Asset';
  id: Scalars['ID'];
  name: Scalars['String'];
  value: Scalars['Float'];
  type: AssetType;
  performanceYTD?: Maybe<Scalars['Float']>;
};

export type Budget = {
  __typename?: 'Budget';
  id: Scalars['ID'];
  name: Scalars['String'];
  limit: Scalars['Float'];
  spent: Scalars['Float'];
  period: Scalars['String']; // e.g., 'Monthly'
};

export type CreditScore = {
  __typename?: 'CreditScore';
  score: Scalars['Int'];
  change: Scalars['Int'];
  rating: Scalars['String'];
  provider: Scalars['String'];
};

export type GamificationState = {
    __typename?: 'GamificationState';
    level: Scalars['Int'];
    levelName: Scalars['String'];
    progress: Scalars['Int'];
    score: Scalars['Int'];
};

export type RewardPoints = {
    __typename?: 'RewardPoints';
    balance: Scalars['Int'];
    lastEarned: Scalars['Int'];
};

export type FinancialGoal = {
    __typename?: 'FinancialGoal';
    id: Scalars['ID'];
    name: Scalars['String'];
    targetAmount: Scalars['Float'];
    currentAmount: Scalars['Float'];
    targetDate: Scalars['Date'];
    aiPlan?: Maybe<Scalars['JSON']>;
};

export type CorporateCard = {
    __typename?: 'CorporateCard';
    id: Scalars['ID'];
    holderName: Scalars['String'];
    cardNumberMask: Scalars['String'];
    status: Scalars['String'];
    frozen: Scalars['Boolean'];
    balance: Scalars['Float'];
    limit: Scalars['Float'];
    controls: CorporateCardControls;
};

export type CorporateCardControls = {
    __typename?: 'CorporateCardControls';
    atm: Scalars['Boolean'];
    contactless: Scalars['Boolean'];
    online: Scalars['Boolean'];
    monthlyLimit: Scalars['Float'];
};

export type FinancialAnomaly = {
    __typename?: 'FinancialAnomaly';
    id: Scalars['ID'];
    description: Scalars['String'];
    details: Scalars['String'];
    severity: AnomalySeverity;
    status: AnomalyStatus;
    timestamp: Scalars['DateTime'];
    riskScore: Scalars['Int'];
};

export type DashboardData = {
    __typename?: 'DashboardData';
    user: User;
    recentTransactions: Array<Transaction>;
    assets: Array<Asset>;
    budgets: Array<Budget>;
    creditScore: CreditScore;
    financialGoals: Array<FinancialGoal>;
};

// ================================================================================================
// INPUT TYPES
// ================================================================================================

export type AddTransactionInput = {
    type: TransactionType;
    category: Scalars['String'];
    description: Scalars['String'];
    amount: Scalars['Float'];
    date: Scalars['Date'];
};

export type CreateFinancialGoalInput = {
    name: Scalars['String'];
    targetAmount: Scalars['Float'];
    targetDate: Scalars['Date'];
};

export type UpdateCorporateCardControlsInput = {
    cardId: Scalars['ID'];
    atm?: InputMaybe<Scalars['Boolean']>;
    contactless?: InputMaybe<Scalars['Boolean']>;
    online?: InputMaybe<Scalars['Boolean']>;
    monthlyLimit?: InputMaybe<Scalars['Float']>;
}

// ================================================================================================
// QUERY TYPE
// ================================================================================================

export type Query = {
  __typename?: 'Query';
  getDashboardData: DashboardData;
  listTransactions(limit?: InputMaybe<Scalars['Int']>, offset?: InputMaybe<Scalars['Int']>, type?: InputMaybe<TransactionType>): Array<Transaction>;
  getTransactionById(id: Scalars['ID']): Maybe<Transaction>;
  getFinancialGoal(id: Scalars['ID']): Maybe<FinancialGoal>;
  listCorporateCards: Array<CorporateCard>;
  getCorporateCard(id: Scalars['ID']): Maybe<CorporateCard>;
  listAnomalies(status?: InputMaybe<AnomalyStatus>): Array<FinancialAnomaly>;
};

// ================================================================================================
// MUTATION TYPE
// ================================================================================================

export type Mutation = {
  __typename?: 'Mutation';
  addTransaction(input: AddTransactionInput): Transaction;
  createFinancialGoal(input: CreateFinancialGoalInput): FinancialGoal;
  freezeCorporateCard(cardId: Scalars['ID']): CorporateCard;
  unfreezeCorporateCard(cardId: Scalars['ID']): CorporateCard;
  updateCorporateCardControls(input: UpdateCorporateCardControlsInput): CorporateCard;
  resolveAnomaly(anomalyId: Scalars['ID'], resolutionNotes: Scalars['String']): FinancialAnomaly;
};

// ================================================================================================
// SUBSCRIPTION TYPE
// ================================================================================================

export type Subscription = {
    __typename?: 'Subscription';
    onNewTransaction: Transaction;
    onAnomalyDetected: FinancialAnomaly;
}

// ================================================================================================
// FRAGMENTS
// ================================================================================================

export type UserDetailsFragment = { __typename?: 'User', id: string, name: string, email: string, gamification: { __typename?: 'GamificationState', level: number, levelName: string, progress: number }, rewardPoints: { __typename?: 'RewardPoints', balance: number } };

export type TransactionDetailsFragment = { __typename?: 'Transaction', id: string, type: TransactionType, status: TransactionStatus, category: string, description: string, amount: number, date: any, carbonFootprint?: number | null, merchant?: { __typename?: 'Merchant', id: string, name: string } | null };

export type CorporateCardDetailsFragment = { __typename?: 'CorporateCard', id: string, holderName: string, cardNumberMask: string, status: string, frozen: boolean, balance: number, limit: number, controls: { __typename?: 'CorporateCardControls', atm: boolean, contactless: boolean, online: boolean, monthlyLimit: number } };


// ================================================================================================
// DOCUMENT NODES & APOLLO HOOKS
// ================================================================================================

export const UserDetailsFragmentDoc = gql`
    fragment UserDetails on User {
      id
      name
      email
      gamification {
        level
        levelName
        progress
      }
      rewardPoints {
        balance
      }
    }
`;

export const TransactionDetailsFragmentDoc = gql`
    fragment TransactionDetails on Transaction {
      id
      type
      status
      category
      description
      amount
      date
      carbonFootprint
      merchant {
        id
        name
      }
    }
`;

export const CorporateCardDetailsFragmentDoc = gql`
    fragment CorporateCardDetails on CorporateCard {
        id
        holderName
        cardNumberMask
        status
        frozen
        balance
        limit
        controls {
            atm
            contactless
            online
            monthlyLimit
        }
    }
`;

export const GetUserDashboardDocument = gql`
    query GetUserDashboard {
      getDashboardData {
        user {
          ...UserDetails
        }
        recentTransactions {
          ...TransactionDetails
        }
        assets {
          id
          name
          value
          type
          performanceYTD
        }
        budgets {
          id
          name
          limit
          spent
        }
        creditScore {
          score
          change
          rating
        }
        financialGoals {
          id
          name
          targetAmount
          currentAmount
        }
      }
    }
    ${UserDetailsFragmentDoc}
    ${TransactionDetailsFragmentDoc}
`;

export function useGetUserDashboardQuery(baseOptions?: Apollo.QueryHookOptions<GetUserDashboardQuery, GetUserDashboardQueryVariables>) {
  const options = {...defaultOptions, ...baseOptions}
  return Apollo.useQuery<GetUserDashboardQuery, GetUserDashboardQueryVariables>(GetUserDashboardDocument, options);
}

export const ListCorporateCardsDocument = gql`
    query ListCorporateCards {
        listCorporateCards {
            ...CorporateCardDetails
        }
    }
    ${CorporateCardDetailsFragmentDoc}
`;

export function useListCorporateCardsQuery(baseOptions?: Apollo.QueryHookOptions<ListCorporateCardsQuery, ListCorporateCardsQueryVariables>) {
    const options = {...defaultOptions, ...baseOptions}
    return Apollo.useQuery<ListCorporateCardsQuery, ListCorporateCardsQueryVariables>(ListCorporateCardsDocument, options);
}

export const AddTransactionDocument = gql`
    mutation AddTransaction($input: AddTransactionInput!) {
      addTransaction(input: $input) {
        ...TransactionDetails
      }
    }
    ${TransactionDetailsFragmentDoc}
`;

export function useAddTransactionMutation(baseOptions?: Apollo.MutationHookOptions<AddTransactionMutation, AddTransactionMutationVariables>) {
  const options = {...defaultOptions, ...baseOptions}
  return Apollo.useMutation<AddTransactionMutation, AddTransactionMutationVariables>(AddTransactionDocument, options);
}

export const FreezeCorporateCardDocument = gql`
    mutation FreezeCorporateCard($cardId: ID!) {
        freezeCorporateCard(cardId: $cardId) {
            ...CorporateCardDetails
        }
    }
    ${CorporateCardDetailsFragmentDoc}
`;

export function useFreezeCorporateCardMutation(baseOptions?: Apollo.MutationHookOptions<FreezeCorporateCardMutation, FreezeCorporateCardMutationVariables>) {
    const options = {...defaultOptions, ...baseOptions}
    return Apollo.useMutation<FreezeCorporateCardMutation, FreezeCorporateCardMutationVariables>(FreezeCorporateCardDocument, options);
}

export const OnNewTransactionSubscriptionDocument = gql`
    subscription OnNewTransaction {
        onNewTransaction {
            ...TransactionDetails
        }
    }
    ${TransactionDetailsFragmentDoc}
`;

export function useOnNewTransactionSubscription(baseOptions?: Apollo.SubscriptionHookOptions<OnNewTransactionSubscription, OnNewTransactionSubscriptionVariables>) {
    const options = {...defaultOptions, ...baseOptions}
    return Apollo.useSubscription<OnNewTransactionSubscription, OnNewTransactionSubscriptionVariables>(OnNewTransactionSubscriptionDocument, options);
}

// Define placeholder types for generated hooks
export type GetUserDashboardQuery = any;
export type GetUserDashboardQueryVariables = any;
export type ListCorporateCardsQuery = any;
export type ListCorporateCardsQueryVariables = any;
export type AddTransactionMutation = any;
export type AddTransactionMutationVariables = any;
export type FreezeCorporateCardMutation = any;
export type FreezeCorporateCardMutationVariables = any;
export type OnNewTransactionSubscription = any;
export type OnNewTransactionSubscriptionVariables = any;
